//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sheets_words")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub sheet_id: i32,
  pub word_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::sheets::Entity",
    from = "Column::SheetId",
    to = "super::sheets::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Sheets,
  #[sea_orm(
    belongs_to = "super::words::Entity",
    from = "Column::WordId",
    to = "super::words::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Words,
}

impl Related<super::sheets::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Sheets.def()
  }
}

impl Related<super::words::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Words.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
